### ISSUE TITLE
Level Complete Dialog

### ISSUE THREAD

**Issue by ManhattanDeveloper** [V-Neck/v-neck.github.io#1]
Text too large

**Comment by ManhattanDeveloper** [comment]
Can't click and drag on mobile. Only tested on Android. Scales beautifully though.

**Comment by V-Neck** [comment]
1.) With jQuery UI, it will only work on desktop, but there are relatively simple work arounds for mobile.
2.) I wrote a function to scale it. It'll work with any screen, any number of boxes
3.) Text is hard. Suggestions?

**Comment by V-Neck** [comment]
I found a library called pep, which seems to extend draggable() to mobile. However, implementation is a little tricky. If you or Dan would like to look into that, I think we would be well on our way to making this public.

**Comment by V-Neck** [comment]
Aw, to remember the past
